name: todo_as_issue
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/HicaroD/TodoAsIssue

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  http: ^0.13.5
